---
title: "StudyCase: Netflix RS"
author: "Diego Lesmes"
date: "10/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(tidyverse)
library(caret)
library(data.table)
library(knitr)
```


## EDA MovieLens Dataset

First is developed the exploratory data analysis to understand the data setup and the  data structure is available from [here](http://files.grouplens.org/datasets/movielens).

So lets go to start:

### Data Available
```{r dim}
edx <- get("edx")
str(edx)
summary(edx) %>% knitr::kable()
dim(edx)
```

## Variables
### Ratings


```{r ratings}
edx %>% group_by(rating) %>% 
  summarise(N_Score = n()) %>% 
  knitr::kable()
```

```{r ratings hist}
hist(edx$rating,col = "light yellow",
     main = "Ratings Predictor",
     xlab = "Rating")
```

### Movies

```{r Movies}
length(unique(edx$movieId))
```

### Users

```{r Users}
length(unique(edx$userId))
```
### Genres

Number of ratings are in each of the following genres

* Drama 

```{r Genres_Drama}
edx %>% filter(str_detect(genres,"Drama")) %>%
  nrow()
```
* Comedy

```{r Genres_Comedy}
edx %>% filter(str_detect(genres,"Comedy")) %>%
  nrow()
```

* Thriller

```{r Genres_Thriller}
edx %>% filter(str_detect(genres,"Thriller")) %>%
  nrow()
```

* Romance

```{r Genres_Romance}
edx %>% filter(str_detect(genres,"Romance")) %>%
  nrow()
```
